Vagrant.configure("2") do |config|
 
    config.vm.define "cicd" do |cicd|
        cicd.vm.box = "ubuntu/xenial64"
        cicd.vm.hostname = "cicd"
        cicd.vm.network "private_network", ip: "10.0.0.4"
    end
 
    config.vm.define "server" do |server|
        server.vm.box = "ubuntu/xenial64"
        server.vm.hostname = "dev"
        server.vm.network "private_network", ip: "10.0.0.5"
    end
 
end
